name: kaney-marketplace
services:
- name: web
  source_dir: /
  github:
    repo: tu-usuario/kaney-marketplace
    branch: main
  run_command: yarn start
  build_command: yarn build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: NODE_ENV
    value: production
